### ISSUE TITLE
Customs songs dont work 1.6

### ISSUE THREAD

**Issue by divine332** [kihecido/BMBF#10]
downloaded and did everything correctly, yet cutomsongs just load and cant be started, anyone else having this issue? is a fix inc?

**Comment by Arakon** [comment]
Working with zero issues here. Try installing BMBF from the APKs and go through setup on the headset instead of the PC side. The behavior you describe is what you get when trying to run BMBF 1.4.5 on Beat Saber 1.6.0.

**Comment by divine332** [comment]
what dafak do you mean? ive gotta install it via the pc ? there is no other way?

**Comment by divine332** [comment]
says bmbf (4206)

**Comment by Arakon** [comment]
Install the APK files for BMBF via SideQuest and then launch BMBF on the Headset. Don't use the PC installer.

**Comment by divine332** [comment]
and how did i start bmbf in the headset again? never done it b4, only via desktop

**Comment by Arakon** [comment]
It'll be in unknown sources, or start OculusTV and find it under "Channels".

**Comment by divine332** [comment]
works, the song with pewdiepie fucking lags out the whole quest though, pls remove from bsaver.
works really well now otherwise! need the mods now :D shame they arent right version yet ;D
