### ISSUE TITLE
Lost custom Playlist folders upon upgrade

### ISSUE THREAD

**Issue by Bjohn55** [kihecido/BMBF#11]
Any ideas how I get these back.  Sorting 500 songs is a pain

**Comment by Arakon** [comment]
Try the following:
- Using sidequest, go to /BMBFData in the file explorer
- Back up config.json and versionInfo.json to your PC, and make another copy of them that you don't touch.
- Open config.json in a text editor, see if your playlists are mentioned in the text somewhere. If not, you can also check the various config.json.backup.x files for the same. If you find one that still has your playlists, name that file config.json.
- Open versionInfo.json in a text editor. Edit the version numbers in there to change Beat Saber version to 1.5.0 and BMBF version to 1.4.5.
- Upload the versionInfo back to your Quest, and the config.json if you had to rename it

Start BMBF on the Quest. It should then inform you that you seem to have upgraded BMBF and ask if you want to restore your Playlists and data. Say yes and it should do just that.

**Comment by Bjohn55** [comment]
Backup 3 had it.  Thank you for the hours of time you saved me
