### ISSUE TITLE
What exactly do I download?

### ISSUE THREAD

**Issue by YeetDogz** [kihecido/BMBF#14]
I have the quest and a windows computer I'm just wondering what asset I have to install

**Comment by YeetDogz** [comment]
I just deleted the com. Apk on my headse

**Comment by YeetDogz** [comment]
I just deleted the com.---- BMBF file in my headset in sidequest. Then I download the APK form the assets and restored my custom songs in the tools menu of BMBF.

**Comment by sonicboom989** [comment]
just wondering how you got to that file in sidequest and how you updated

**Comment by infinitemonkeytheory** [comment]
Go [here](https://github.com/kihecido/BMBF/releases)

<img width="844" alt="Screenshot 2019-12-21 at 17 43 27" src="https://user-images.githubusercontent.com/7156072/71315757-6b3a8100-2419-11ea-996c-1bbd3c55b5d3.png">

Grab both apks.  Install each via SideQuest (see [here](https://github.com/the-expanse/SideQuest/wiki/How-can-i-manually-install-apps))
