### ISSUE TITLE
syncsaber bookmark limit of 200 too small

### ISSUE THREAD

**Issue by billross00** [kihecido/BMBF#15]
I have close to 300 bookmarks on bsaber.
I would like to install all of these using syncsaber
It appears the limit is 200.
Is there any reason the limit can't be much higher like 500?
Also if there are more than the limit, how does it select the bookmarks to use.

Do you have any suggestions how I can get 300 bookmarked songs into bmbf?

**Comment by YeetDogz** [comment]
I'm not sure if you have done this already but in the tools tab at the top of BMBF there is an option to restore playlists (or something like that). It worked for my 120 songs. I don't know if the cap is still at 200. But I hope this helps.

**Comment by billross00** [comment]
Thanks,

I think the tools/reload songs folder button reloads all the songs in the customSongs directory.
I couldn't tell if there is a limit for that.
I am still trying to use the bsaber bookmark system to keep track of my songs.
I am trying to figure out how to get more than 200 bookmarked songs to download.
I tried moving them out of the bookmarks folder but that didn't help.
Is there someone who knows the details of how the bmbf syncsaber works?

I also have a list of other issues I have come across but I didn't want to report alot of issues I can deal with.
Is there a way to communicate with the bmbf developers?

Thanks again

Bill Ross


________________________________

**Comment by billross00** [comment]
I figured out that if you decrease the number of songs it goes to infinity symbol.
This worked for more than 200 songs.
I did notice that the number of songs queued and the number of bookmarks was not the same.
Not sure of an easy way to verify which songs didn't get queued.
I ran the download a second time and it seemed to pull a few more songs, but still not all
