### ISSUE TITLE
songs stuck loading forever

### ISSUE THREAD

**Issue by sonicboom989** [kihecido/BMBF#19]
I updated my beat saber to the latest version (the 360 one) and I reinstalled BMBF. I did the quick fix, made sure I had the latest version installed, and reinstalled everything again but every time I try and play one of my custom songs, it just keeps loading and no buttons come up so I can't play them. BTW I'm on quest

**Comment by Arakon** [comment]
Update BMBF, not just the game.
https://github.com/kihecido/BMBF/releases/tag/v1.5.0
Use the APKs, not the installer.

**Comment by sonicboom989** [comment]
how do I do that I'm confused

**Comment by sonicboom989** [comment]
sorry I'm not very good with knowing this stuff I'm kind of new to it
