### ISSUE TITLE
Songs stuck loading 

### ISSUE THREAD

**Issue by Stellular** [kihecido/BMBF#27]
I have BS 1.6 and BMBF 1.5.0 and i have some songs that just arent loading. I would provide pictures but idk how to upload pictures from my quest to my pc yet or i havent even tried.

**Comment by JiveOff** [comment]
For some songs, you will need Mapping Extensions, a quest mod that you can find [here](https://cdn.discordapp.com/attachments/654964358044057603/655856233126821920/MappingExtensions_0.15.0.zip).

Just drop the zip in the Upload section of BMBF and done.

**Comment by Terifictaylor10** [comment]
I added the mapping extensions but it messed up all my beatmaps now where the notes fly way over to the left and I cant play any levels anymore

**Comment by micfogas** [comment]
that's an issue with mapping extensions then. with each major revision change, beat saber gets new major features, some of which may conflict with mods designed for older versions. unless you have confirmed it works or know how to undo any changes you make, it's best not to use mods until they are announced to be working with the latest release.




I'm sure he will update mapping extensions when he's able. until then, disable it. if that doesn't fix it, you will probably have to reload assets from with bmbf on the tools tab. 




On Sat, Feb 1, 2020 at 10:24 PM -0800, "Terifictaylor10" <notifications@github.com> wrote:












I added the mapping extensions but it messed up all my beatmaps now where the notes fly way over to the left and I cant play any levels anymore
