### ISSUE TITLE
Restore custom songs data ?

### ISSUE THREAD

**Issue by TheZeldaBoss** [kihecido/BMBF#29]
Hello,

I recently uninstalled my cracked beatSaber version to get a paid one (and to update it), and I'd like to restore the custom songs that I had previously from BMBF and BeatSaver/BeastSaber... Is there a way to do that ? I didn't find any informations about it...
I still have songs data on my Oculus Quest, but there is nothing to add it directly to BMBF...

**Comment by micfogas** [comment]
I think we're all glad that you are no longer using a pirated copy of the game, as that is not the purpose this was created for, and pirating is one of the reasons that Facebook has taken are harder stance again sideloading and modding. Supporting developers, especially VR developers (whether they are AAA or indie) is how VR will stay alive. Oculus doesn't profit from the headsets. They actually take a slight loss. The profitability comes from the Oculus store and app purchases. Plus, using legit copies is not only safer, but less stressful.




There is a folder on your Quest named BMBFData. Inside this folder is where the unmodded apk, CustomSongs, and other data is stored. Basically everything that BMBF and the BMBF-modded Beat Saber use. When you installed the legal copy and modded it with BMBF, did you try opening BMBF on the Quest, going to Tools, and reloading the custom songs folder? That will force BMBF to scan the folder and rebuild the song json file. Try that.




tech




On Sat, Jan 4, 2020 at 10:14 AM -0800, "Benoit Tachet" <notifications@github.com> wrote:












Hello,


I recently uninstalled my cracked beatSaber version to get a paid one (and to update it), and I'd like to restore the custom songs that I had previously from BMBF and BeatSaver/BeastSaber... Is there a way to do that ? I didn't find any informations about it...

I still have songs data on my Oculus Quest, but there is nothing to add it directly to BMBF...

**Comment by micfogas** [comment]
Oh, and regarding restoring songs from BeatSaver/BeastSaber, if you used SyncSaber to load them onto your Quest, you can go to the SyncSaber tab in BMBF, re enter your username, set your preferred settings back again, and click Queue Downloads to resync that.




On Sat, Jan 4, 2020 at 10:14 AM -0800, "Benoit Tachet" <notifications@github.com> wrote:












Hello,


I recently uninstalled my cracked beatSaber version to get a paid one (and to update it), and I'd like to restore the custom songs that I had previously from BMBF and BeatSaver/BeastSaber... Is there a way to do that ? I didn't find any informations about it...

I still have songs data on my Oculus Quest, but there is nothing to add it directly to BMBF...
