### ISSUE TITLE
Beat Saber just does not start.

### ISSUE THREAD

**Issue by T0niMichel** [kihecido/BMBF#3]
It just does not start.

**Comment by curvatura99** [comment]
It's because the permissions on the storage are reset. Change the permission by clicking on the 3 dots in the lower right corner of the app while in the library. Choose permissions, then move the slider to allow storage access.

**Comment by T0niMichel** [comment]
Sorry to say that, but I have checked the hook to allow storage access and started BS via BMBF.
It still does not start! I am left in a black room where I can see the three dots indicating that the device is loading the app.

**Comment by curvatura99** [comment]
Did you reboot or force close the app through Android setting before restarting? Also if you have the mapping extensions mod installed you need to delete it since as it will hang when loading Beat Saber. If you want the mod you need to install version 14.1.

**Comment by T0niMichel** [comment]
Here are the steps I took:

1. Removed/Uninstalled the BS via SideQuest
2. reinstalled BS 
3. Run BMBF v1.4.5 from unknown sources -> uninstall BS -> patch BS -> install BS -> done
4. granted permissions to BS like you said
5. Download custom song -> sync -> start BS (via BMBF)

well I would give BS 14.1 a shot... is there a sourec where I can get the apk from?

**Comment by curvatura99** [comment]
Glad you got it going. Here's the mapping extensions I compiled the other day:

[MappingExtensions.zip](https://github.com/kihecido/BMBF/files/3843994/MappingExtensions.zip)

Just drop the files/folder in /BMBFData/Mods and then enable via BMBF. You can get Kyle1413's version on the Beat Saber Mod Discord server:

https://discord.gg/beatsabermods

**Comment by micfogas** [comment]
what system did you use to compile? I was having issues with win64 Android studio. his beatsaberhooks pull didn't have the libil2cpp 




On Wed, Nov 13, 2019 at 4:10 PM -0800, "curvatura99" <notifications@github.com> wrote:












Glad you got it going. Here's the mapping extensions I compiled the other day:


MappingExtensions.zip


Just drop the files/folder in /BMBFData/Mods and then enable via BMBF. You can get Kyle1413's version on the Beat Saber Mod Discord server:


https://discord.gg/beatsabermods

**Comment by curvatura99** [comment]
I used Android NDK r20b for Linux and extracted the libil2cpp from the Unity installer. Beat saber uses version 2018.4.4:

https://developer.android.com/ndk/downloads
https://unity3d.com/get-unity/download/archive

I had to modify a couple of symlinks, but was able to compile everything pretty easy.

**Comment by T0niMichel** [comment]
Sorry it is still not starting!

**Comment by stealthybox** [comment]
@T0niMichel I was able to update from BeatSaber 1.4.3 to 1.5.0 tonight and re-patch /w BMBF.

The Sticky on the BSMG discord is helpful:
- https://discordapp.com/channels/441805394323439646/599740612752703490/643762036639137803
- https://discordapp.com/channels/441805394323439646/599740612752703490/644458122366287876

This video also makes it pretty clear:
- https://www.youtube.com/watch?v=JGCf01gX4nU

I did have to click the 3 dots before launching and add Storage permission as mentioned here. That's not mentioned very well in the sticky.

With BS 1.5.0, I was able to keep my CustomSongs and restore settings, leaderboard, and campaign data, as well as install MappingExtensions 0.14.1. (see `#quest-mods` on discord)

**Comment by micfogas** [comment]
curv, when you get the chance can you push your beatsaberhook folder to the repo so it's in line with the 14.1 source? or did you fork it? would be great to have that merged into kihecido's repo




On Wed, Nov 13, 2019 at 10:54 PM -0800, "curvatura99" <notifications@github.com> wrote:












I used Android NDK r20b for Linux and extracted the libil2cpp from the Unity installer. Beat saber uses version 2018.4.4:


https://developer.android.com/ndk/downloads

https://unity3d.com/get-unity/download/archive


I had to modify a couple of symlinks, but was able to compile everything pretty easy.

**Comment by curvatura99** [comment]
> EDIT: I just realized this is on the BMBF repo. I'll see about merging the updated beatsaberhook to Kylemc1413's repo for mappingextensions, later.

I don't want to push the libil2cpp libraries since that's Unity's. We should have a version sticky with a link to let other's know.
