### ISSUE TITLE
Songs inside Playlists do not come back after Restore

### ISSUE THREAD

**Issue by UltimateRJ** [kihecido/BMBF#30]
When restoring BMBF the playlists themselves are restored but not the songs inside, they are left empty

**Comment by isaiah778** [comment]
I am also running into this issue. I just updated to BS 1.6.1 and after install BMBF I found I had playlists but no songs. When I reload the songs, they didn't go to their proper playlist either. They were all mixed together in the Custom Songs folder.

**Comment by harryofbath** [comment]
This happened to me aswell. I tried restoring from backup as per the wiki instructions, but my songs are not in the correct playlist and none of my scores are present

**Comment by tronage** [comment]
Same for me.  It offers a popup "you just upgraded BMBF would you like to restore your playlists" message.  I click yes, and then it bombs out with like 200+ errors saying it can't add the song to the playlist.  I uploaded my logs from within BMBF if that helps.  The only way to get music listed, it ro reload the music tracks, then they all come back, but all in the default list, with all the custom playlists empty.  There should be a button to reload your playlists to put the songs back where they belong.  So much effort and time to sort them is now wasted.
