### ISSUE TITLE
BMBF not working in the new camellia update.

### ISSUE THREAD

**Issue by patfr** [kihecido/BMBF#39]
I know that it makes sense it doen't work this is just for letting the creator know. (Sorry if my english is bad)

**Comment by REBELinBLUE** [comment]
Hopefully not long, I normally backup the APK for beatsaber but completely forgot to this time 😭

**Comment by ClassicGOD** [comment]
BMBF 1.5.0.0 works fine with the 1.7.0 version of BeatSaber for me. You just can't restore your music folder and have to sync it up again (or the Camellia pack will be removed). I just said no to restore after patching the apk and synced my bookmarks.

**Comment by patfr** [comment]
oh ok thanks
