### ISSUE TITLE
Forever loading

### ISSUE THREAD

**Issue by 1Mist1** [kihecido/BMBF#43]
After i get done installing all of my song and launch up beat saber it just loads forever

**Comment by Bomberus** [comment]
Did you install the mapping extension?

**Comment by 1Mist1** [comment]
> Did you install the mapping extension?

What mapping extension and where do I get it from?

**Comment by Bomberus** [comment]
Mapping Extension can be loaded from discord server: https://discord.gg/beatsabermods 
Please note it is not yet available for 1.7
This should solve the issue that some songs load forever.

If all your custom songs load for ever, did you set the storage permission, for the beat saber app?

**Comment by 1Mist1** [comment]
> Mapping Extension can be loaded from discord server: https://discord.gg/beatsabermods
> Please note it is not yet available for 1.7
> This should solve the issue that some songs load forever.
> 
> If all your custom songs load for ever, did you set the storage permission, for the beat saber app?

My game wont load not my songs I cant launch beat saber
