### ISSUE TITLE
BeatSync doesn't work?

### ISSUE THREAD

**Issue by jacwib** [kihecido/BMBF#47]
I threw a couple of songs into my bsaber bookmarks, entered my username in BMBF (miniwa), and hit the button....

It loaded for a second, and then nothing.

(I try hitting it again a few times, still nothing. :x)

Anyone have a similar issue?

**Comment by micfogas** [comment]
do the other playlists sync? you could test one of the scoresaber/beastsaber/beatsaver ones by enabling it and setting a low number, for testing. you can delete it afterward and untick it. if everything else works fine, double-check the spelling of your username maybe? I've testing everything except the syncing. I'm a masochist who backs up the whole bmbfdata folder and then copies the songs back into the customsongs folder after reinstalling. a quick reload songs folder and I have it all back. minus the playlists of course. everything works fine for me, including my favorite saber mof, trail mod, score visualizer and map extensions, on 1.7.0. 




I'll test out the syncing later and see if I have an issue




On Wed, Feb 12, 2020 at 5:39 AM -0800, "Jack Wiberg" <notifications@github.com> wrote:












I threw a couple of songs into my bsaber bookmarks, entered my username in BMBF (miniwa), and hit the button....


It loaded for a second, and then nothing.


(I try hitting it again a few times, still nothing. :x)


Anyone have a similar issue?

**Comment by jacwib** [comment]
i am an idiot.
