### ISSUE TITLE
Beat Saber Stuck at ... Loading Screen

### ISSUE THREAD

**Issue by gorfreed** [kihecido/BMBF#5]
I have tried everything with BMBF by now - it is simply not working for me and I am surprised that it worked for you all. 

I have manually installed it via Sideloader. I have installed it via the Windows installer. I have at one point even reset my Oculus Quest back to factory settings. It simply doesnt work.

I have tried all troubleshooting advice, e.g. checked the permission settings, started the game one time before applying BMBF, etc.

The log doesn't give any clue about what could be the issue (please see below).

I would be really surprised if somebody here can actually confirm BMBF is working for them on the latest Beatsaber version.

2019-12-06 02:32:57.949: MSG: Serializing all assets...
2019-12-06 02:32:57.953: MSG: File sharedassets0.assets has changed, writing new contents.
2019-12-06 02:32:58.975: MSG: External file f7f5ecabb5334914d9aaecd82e4b5adb is not already references from this file sharedassets0.assets.  Adding reference with what is hopefully the correct values.
2019-12-06 02:32:59.145: MSG: External file 1c2bd565f234a9f498a04b49ebe0d223 is not already references from this file sharedassets0.assets.  Adding reference with what is hopefully the correct values.
2019-12-06 02:33:04.883: MSG: File sharedassets22.assets has changed, writing new contents.
2019-12-06 02:33:06.618: MSG: Serialization of assets took 8669ms
2019-12-06 02:33:06.618: MSG: Making sure everything is saved...
2019-12-06 02:33:06.618: MSG: ModManager has no changes, not saving it.
2019-12-06 02:33:06.618: MSG: Starting Performing queued file operations...
2019-12-06 02:33:06.646: MSG: Finished Performing queued file operations in 27 ms
2019-12-06 02:33:06.649: MSG: Rolling config backup config.json.backup.2 to config.json.backup.3
2019-12-06 02:33:06.650: MSG: Rolling config backup config.json.backup.1 to config.json.backup.2
2019-12-06 02:33:06.651: MSG: Rolling config backup config.json.backup.0 to config.json.backup.1
2019-12-06 02:33:06.652: MSG: Rolling config backup config.json to config.json.backup.0
2019-12-06 02:33:06.684: MSG: Backing up PlayerData.dat

**Comment by micfogas** [comment]
well, I can confirm it's working. in fact, I just reset my quest the other day. had to redo beat saber and bmbf.




aside from the logs you included, you haven't given much detail regarding what you're experiencing. and essentially implying that the product can't work for anyone if it's not working for you, isn't going to get you much support from people here. a better approach would be to say exactly what is/isn't happening, the steps you've performed in detail, and asking if anyone is willing to help you and work with you as much as possible to get it working for you. you didn't actually ask for any help. but I'm willing to spend a little time responding and trying to help you with it.




i don't see the installer failing, so can you describe, in as much detail as possible, the steps you perform from starting with installing beat saber from the Oculus store, and ending with the problem you're experiencing? does the installer appear to complete? does beat saber not run properly? do you see the splash screen and then nothing but a black screen? does the installer show that it's not installed when you re-open it after running? do you get prompted to install the modified apk? 




the program does work, so there must be some little step, however minor it may be, that is getting overlooked. the more detail you provide, the better chance there is of quickly figuring it out and getting it working for you.








On Thu, Dec 5, 2019 at 5:36 PM -0800, "gorfreed" <notifications@github.com> wrote:












I have tried everything with BMBF by now - it is simply not working for me and I am surprised that it worked for you all.


I have manually installed it via Sideloader. I have installed it via the Windows installer. I have at one point even reset my Oculus Quest back to factory settings. It simply doesnt work.


I have tried all troubleshooting advice, e.g. checked the permission settings, started the game one time before applying BMBF, etc.


The log doesn't give any clue about what could be the issue (please see below).


I would be really surprised if somebody here can actually confirm BMBF is working for them on the latest Beatsaber version.


2019-12-06 02:32:57.949: MSG: Serializing all assets...

2019-12-06 02:32:57.953: MSG: File sharedassets0.assets has changed, writing new contents.

2019-12-06 02:32:58.975: MSG: External file f7f5ecabb5334914d9aaecd82e4b5adb is not already references from this file sharedassets0.assets.  Adding reference with what is hopefully the correct values.

2019-12-06 02:32:59.145: MSG: External file 1c2bd565f234a9f498a04b49ebe0d223 is not already references from this file sharedassets0.assets.  Adding reference with what is hopefully the correct values.

2019-12-06 02:33:04.883: MSG: File sharedassets22.assets has changed, writing new contents.

2019-12-06 02:33:06.618: MSG: Serialization of assets took 8669ms

2019-12-06 02:33:06.618: MSG: Making sure everything is saved...

2019-12-06 02:33:06.618: MSG: ModManager has no changes, not saving it.

2019-12-06 02:33:06.618: MSG: Starting Performing queued file operations...

2019-12-06 02:33:06.646: MSG: Finished Performing queued file operations in 27 ms

2019-12-06 02:33:06.649: MSG: Rolling config backup config.json.backup.2 to config.json.backup.3

2019-12-06 02:33:06.650: MSG: Rolling config backup config.json.backup.1 to config.json.backup.2

2019-12-06 02:33:06.651: MSG: Rolling config backup config.json.backup.0 to config.json.backup.1

2019-12-06 02:33:06.652: MSG: Rolling config backup config.json to config.json.backup.0

2019-12-06 02:33:06.684: MSG: Backing up PlayerData.dat

**Comment by gorfreed** [comment]
I tried all the different approaches as I have described them in my post here, it is no exaggeration, all of them lead to the same result, which is the endlessly looping "..." loading screen.
I am really not sure how to offer you more detail here but sure, here are all the steps I have followed for the installer.

1. I am opening the BMBFInstaller and start the process.
2. The process completes successfully.
3. I am opening Beat Saber on the Quest. The app doesn't open.

I skipped the description about me clicking "next" and "confirm" in the BMBFInstaller.
I can totally understand that this is not a lot but this mirrors my frustration. Even the simplest way of installing BMBF leads to the same bug as any other, which leads me to believe there is a general problem with it.
I am also far from the only person stuck at the "...", but maybe not everyone in the Youtube channels and forums knows their way around GIT.

**Comment by mailer2010** [comment]
Go the same problem here too. Did a fresh installation of the latest BeatSaber and the 2 BMBF Apks.
After installation on first real launch of BMBF I shortly see "Start BeatSaber" on the top right. 
Then the red infobox about resetting assets. 
After the the "loading configuration 5 - 90 seconds" message. But nothing happens.

I did use BeatOn before. But Beat On and BeatSaber were completely uninstalled. Maybe gorfreed used Beaton too before?

I also think there might be some leftover files. But I do not want to completely reset my Quest.
Which files should I delete manually?

**Comment by mailer2010** [comment]
My fault. Sorry.
I accidentially downloaded the wrong version of BMBF. For some reason the latest version ist second from the top on guthub page. Using the real latest version worked for me now.

**Comment by gorfreed** [comment]
@mailer2010  Indeed, I used BeatOn before as well!

Indeed, the releases are not in the right order on the releases page, I didn't notice that and just used the installer from the top entry. I just compared the installer files from the two most recent releases though, and they are identical down to the byte. I am pretty sure they are the same. Are you sure the installer you used successfully isn't the same as the one you used before? Maybe you did something different this time around, had the game uninstalled in a specific way maybe?

**Comment by mailer2010** [comment]
Hello gorfreed,

the installer looked the same, but the wrong one showed me "Beat On" on the lower left corner (when the error appeared). With the other installer (both files) it shows BMBF and the error was gone.

However: Before finding out this, I manually deleted every folder on the quest containing BMBF and Beaton (had to disable developer mode for that, than i deleted the files via windows Explorer).

It did not work after deleting the files. Only after then, I realized I was using the wrong apk files. 
They work fine.

**Comment by zolern** [comment]
I think the main misunderstanding here is that if you start BMBF installer from PC it is just not working (at this moment for sure). 

You need to install BMBF APKs (vie SideQuest is the easiest way) to your Oculus Quest and then start BMBF application FROM OCULUS QUEST (Navigate / Library / Unknown Sources / BMBF). After that just follow the installation wizard to modify BeatSaber, that's all.

Of course if you already has unsuccessful BMBF trying you need at first to clean-up your BeatSaber installation, but only first two steps from mailer2010 list are required (I mean 1. Remove BeatSaber and 2. Remove BMBF applications from you Oculus Quest via SideQuest), after that you should install BeatSaber from Oculus Store.

**Comment by douglasg14b** [comment]
Also having this issue after installing from the apk...

It just loads indefinitely.

**Comment by douglasg14b** [comment]
Ah, I didn't use both apks. Could basic instructions be added to the release page?

**Comment by gorfreed** [comment]
@douglasg14b Could you please clarify how you use "both apks"? 
BMBF is now working for you?

**Comment by douglasg14b** [comment]
There are two APK downloads under releases, BMBF and the wrapper. There are no instructions that mention which to use, so I used the larger one, and had this issue.

During the steps @mailer2010 posted, to use both APKs I drug them both into SideQuest at the same time and it added them in.

**Comment by mailer2010** [comment]
Douglas14b,
make sure you use the latest version of the apks. They are not on top of the list on the releases-pages.
You need to use v1.4.5.

After I realized my mistake, using 1.4.3 (the version on top of the list, which loaded indefinitely too) and used 1.4.5 instead, everything worked fine

**Comment by gorfreed** [comment]
Well, with a new version of BS released, most likely all the troubleshooting is obsolete by now anyways. It just think it is a bit annoying to see streamers touting this solution to be working effortlessly when they are obviously using some old version. The people looking for custom songs on Quest must also be a lot fewer than I originally thought. Everyone who cares is here :)

**Comment by micfogas** [comment]
honestly, I wasn't aware of a new version until this thread. update doesn't show for me. weird. I definitely care. until I can get my Kinect 2.0 working as an external sensor for use with link, quest is the way to play. since I don't have a cv1.




On Fri, Dec 13, 2019 at 11:54 AM -0800, "gorfreed" <notifications@github.com> wrote:












Well, with a new version of BS released, most likely all the troubleshooting is obsolete by now anyways. It just think it is a bit annoying to see streamers touting this solution to be working effortlessly when they are obviously using some old version. The people looking for custom songs on Quest must also be a lot fewer than I originally thought. Everyone who cares is here :)
