### ISSUE TITLE
bmbf isn't opening on new version of beat saber

### ISSUE THREAD

**Issue by dijkmeneer** [kihecido/BMBF#57]

**Comment by henwill8** [comment]
It hasnt been updated yet. I suggest going back to 1.7.0 until it is.

**Comment by jake0340** [comment]
Ik I have the same problem

**Comment by kihecido** [comment]
thanks! we are on it!

**Comment by RIz017** [comment]
My BMBF is still not working with the current version of beat saber. I have uninstalled and reinstalled both beat saber and bmbf accordingly to the instructions yet it still wont open bean saber and bmbf is stuck on "loading configuration". a little error message appears in the bottom of bmbf saying it can't run right now

**Comment by ARandomWeeb** [comment]
Same

**Comment by Rayn322** [comment]
BMBF hasn't been updated yet. Wait for BMBF 1.8 to come out and try again. Make sure to use a fresh copy of beat saber

**Comment by jjpokey** [comment]
do these updates usually take a few days? I mean typically speaking. This is the first time i've ever tried using sidequest and finding some of this informaiton isnt very easy

**Comment by Rayn322** [comment]
One time it took less than 24 hours, another time it took around a week. You never really know.
