### ISSUE TITLE
Does BMBF work with latest BS?

### ISSUE THREAD

**Issue by avib99** [kihecido/BMBF#6]
Does BMBF work with latest BS?

**Comment by Dart-Alex** [comment]
Nope, it installs it, the custom songs appear, but you can't play any of the modded songs. Wait for an update :p

**Comment by ryanlauderbach** [comment]
It doesn't, wait for an update.

**Comment by kihecido** [comment]
We're trying!

**Comment by ChrisDoesStuff2** [comment]
> We're trying!

It'll be worth the wait 😁

**Comment by v31cr0** [comment]
Installed the overnight release. Web interface doesn't seem to be letting me add custom tracks at the moment. Not sure if that's a functionality restriction (having just caught up on the ToS change), a bug foe me or a bug for further re-work.

**Comment by ryanlauderbach** [comment]
Are you using a fresh install of BS?

**Comment by v31cr0** [comment]
> Are you using a fresh install of BS?
> […](#)

Yep, downloaded new version onto Quest to get the GD pack and access to the 90/360
