### ISSUE TITLE
unable to restore game save with sidequest

### ISSUE THREAD

**Issue by XBEN314** [kihecido/BMBF#65]
Hello,
Unable to recover game backup via sidequest.
I restored them after moding the game ...
BeatSaber app bug, apllication stopped working.
But how can I recover my progress?
Thanks

**Comment by divvychu** [comment]
@XBEN314 were you able to resolve this?  I tried restoring appdata from my 1.7 setup and BS went into crash loops -- so lost all my progress as well (campaign and party scoring)
