### ISSUE TITLE
Bookmarks not syncing 

### ISSUE THREAD

**Issue by zarev** [kihecido/BMBF#71]
Hi, I am not able to sync any bookmarks anymore for some reason. When I add a bookmark from the website it doesn't show up on syncsaber. None of the other custom playlists like Top 10, Trending etc work either. Any ideas?

**Comment by nothingAD** [comment]
Having the same issue here. Will try to reinstall bmbf and see what happens

**Comment by markhicken** [comment]
Try the latest nightly. Worked for me.
https://bmbf.dev/nightly

**Comment by 41g54h2** [comment]
Hi, I am unable to sync too. In fact, I am unable to download any songs. Every time I click the download arrow, the message "download failed" appears. Any idea why? This is my first time installing bmbf and I followed every step. I know sometime my internet connection is very slow for download. Do you think it could have an impact?

**Comment by markhicken** [comment]
No. I think there is a bad URL or an expired API key or something in the release. Use SideQuest to uninstall BMBF and then download the latest nightly build and install it instead.

**Comment by zarev** [comment]
It appears to be an issue with the release build, but I am not the expert. Currently waiting for @kihecido and team for input.

**Comment by 41g54h2** [comment]
ok, yeah that is exactly what the message says. I will try. Do I have to uninstall beatsaber again before installing nightly?

**Comment by markhicken** [comment]
I don’t think so, but I’m not 100% sure. Give it a try and let us know!

**Comment by zarev** [comment]
@markhicken I am weary of installing anything non-release, seeing that even the official releases sometimes have a hiccup or two. are you confident they are stable?

**Comment by markhicken** [comment]
Absolutely not. But as a software engineer myself, I know you build on what last worked. 

I haven’t noticed any issues with it in the last few days. Also, you could join the discord if you want the latest info.

**Comment by zarev** [comment]
Cool, is that the either BeastSaber or Beat Saber Modding discord or is there a BMBF specific?

**Comment by markhicken** [comment]
Deets here...
https://bmbf.dev/

**Comment by 41g54h2** [comment]
It works! Thank you!!!
