### ISSUE TITLE
im pissed of 

### ISSUE THREAD

**Issue by stuart20202** [kihecido/BMBF#87]
right what the hell is going on ive lost all my songs since you came out with a new update ive lost all my songs i cant even log it nothing happens it toke me a while to make a song list now there all gone so when is this going to get fixed

**Comment by Jverm84** [comment]
Same

**Comment by ADoofus** [comment]
@stuart20202 Calm down please. 
1. It is not the bmbf update's fault. 
2. Bmbf songs auto save. If you weren't prompted to restore songs, try clicking reset assets in the tools tab.
3. Not being able to log in is a bug that has been happening for a while and there is no fix atm.

**Comment by stuart20202** [comment]
im fine but i cant play any songs or anything

**Comment by Bomberus** [comment]
Isn‘t it your fault for not creating backups? Also github issues are not tracked

**Comment by stuart20202** [comment]
shut up i did
